from __future__ import annotations

import argparse
import json
import sys

from audit import audit_domains
from compare_audits import compare_audit_reports
from config import (
    AUDIT_MODE_CONFIGS,
    DEFAULT_CRAWL_SOURCE,
    DEFAULT_AUDIT_MODE,
    DEFAULT_DELAY,
    DEFAULT_DISCOVER_PROVIDER,
    DEFAULT_QUALIFY_MODE,
    QUALIFY_MODE_CONFIGS,
)
from discover import discover_domains, discovery_to_console_rows, import_domains_from_file
from doctor import format_doctor_results, run_doctor
from gsc import run_gsc_analysis
from qualify import qualify_domains
from utils import CLIError, parse_csv_list
from web_ui import launch_ui


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Prospect Machine - SEO prospecting toolkit",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python3 prospect_machine.py discover --niches \"padel,yoga,velo\" --limit 100 --output data/domains_raw.csv\n"
            "  python3 prospect_machine.py qualify data/domains_raw.csv --output data/domains_scored.csv\n"
            "  python3 prospect_machine.py audit data/domains_scored.csv --top 20 --output-dir reports/audits\n"
            "  python3 prospect_machine.py compare-audits reports/audits/old.json reports/audits/new.json\n"
            "  python3 prospect_machine.py gsc exports/pages_recent.csv exports/pages_old.csv -q exports/queries.csv "
            "--html reports/client.html --output reports/client.csv --json reports/client.json\n"
        ),
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    discover_parser = subparsers.add_parser("discover", help="Find domains from niches")
    discover_parser.add_argument("--niches", help="Comma-separated niches, e.g. 'padel,yoga'")
    discover_parser.add_argument(
        "--domains-file",
        help="Optional text file with one domain or URL per line, to bypass live search",
    )
    discover_parser.add_argument("--limit", type=int, default=100, help="Maximum number of unique domains")
    discover_parser.add_argument("--provider", default=DEFAULT_DISCOVER_PROVIDER, help="Search provider name")
    discover_parser.add_argument(
        "--query-mode",
        default="auto",
        choices=["auto", "exact", "expand"],
        help="How to interpret niches: auto, exact, or expand",
    )
    discover_parser.add_argument("--delay", type=float, default=DEFAULT_DELAY, help="Delay between search queries")
    discover_parser.add_argument("--output", default="data/domains_raw.csv", help="CSV output path")

    qualify_parser = subparsers.add_parser("qualify", help="Score domains from domains_raw.csv")
    qualify_parser.add_argument("input_csv", help="Input CSV generated by discover")
    qualify_parser.add_argument("--output", default="data/domains_scored.csv", help="CSV output path")
    qualify_parser.add_argument("--json", dest="json_output", help="Optional JSON output path")
    qualify_parser.add_argument(
        "--mode",
        default=DEFAULT_QUALIFY_MODE,
        choices=sorted(QUALIFY_MODE_CONFIGS),
        help="Qualification mode optimized for fast prospecting or deeper review",
    )
    qualify_parser.add_argument("--delay", type=float, default=DEFAULT_DELAY, help="Delay between homepage requests")
    qualify_parser.add_argument(
        "--check-sitemap",
        action="store_true",
        default=None,
        help="Force sitemap lookup even in fast mode",
    )
    qualify_parser.add_argument(
        "--skip-sitemap",
        action="store_false",
        dest="check_sitemap",
        help="Force skipping sitemap lookup",
    )
    qualify_parser.add_argument("--max-html-bytes", type=int, help="Maximum HTML bytes to load for homepage analysis")
    qualify_parser.add_argument("--max-total-seconds-per-domain", type=float, help="Hard time budget per domain")
    qualify_parser.add_argument("--max-total-requests-per-domain", type=int, help="Hard request budget per domain")
    qualify_parser.add_argument("--max-sitemap-urls", type=int, help="Maximum sitemap URLs kept for estimation")
    qualify_parser.add_argument("--max-nested-sitemaps", type=int, help="Maximum nested sitemaps to inspect")

    audit_parser = subparsers.add_parser("audit", help="Deep audit on scored domains")
    audit_parser.add_argument("input_csv", nargs="?", help="Input CSV generated by qualify")
    audit_parser.add_argument("--site", help="Audit one site directly without CSV")
    audit_parser.add_argument(
        "--mode",
        default=DEFAULT_AUDIT_MODE,
        choices=sorted(AUDIT_MODE_CONFIGS),
        help="Audit mode optimized for lightweight prospecting or deeper review",
    )
    audit_parser.add_argument("--top", type=int, help="Only audit the top N domains")
    audit_parser.add_argument("--min-score", type=int, help="Only audit domains with score >= this value")
    audit_parser.add_argument("--output-dir", default="reports/audits", help="Directory for JSON reports")
    audit_parser.add_argument("--delay", type=float, default=DEFAULT_DELAY, help="Delay between crawl requests")
    audit_parser.add_argument("--max-pages", type=int, help="Maximum pages per site")
    audit_parser.add_argument("--max-depth", type=int, help="Maximum crawl depth from the starting page")
    audit_parser.add_argument("--max-total-requests-per-domain", type=int, help="Maximum requests per domain")
    audit_parser.add_argument("--max-links-per-page", type=int, help="Maximum links enqueued per crawled page")
    audit_parser.add_argument("--max-html-bytes", type=int, help="Maximum HTML bytes to load per page")
    audit_parser.add_argument("--max-total-seconds-per-domain", type=float, help="Hard time budget per domain")
    audit_parser.add_argument("--overlap", action="store_true", dest="overlap_enabled", default=None, help="Force overlap analysis on")
    audit_parser.add_argument("--skip-overlap", action="store_false", dest="overlap_enabled", help="Disable overlap analysis")
    audit_parser.add_argument("--overlap-max-pages", type=int, help="Maximum pages considered for overlap analysis")
    audit_parser.add_argument(
        "--crawl-source",
        default=DEFAULT_CRAWL_SOURCE,
        choices=["home", "sitemap", "mixed"],
        help="Seed crawl from homepage, sitemap URLs, or both",
    )
    audit_parser.add_argument("--sitemap-max-urls", type=int, help="Maximum sitemap URLs used as crawl seeds")
    audit_parser.add_argument("--skip-robots", action="store_true", help="Do not check robots.txt before crawling URLs")
    audit_parser.add_argument("--html", dest="html_output", help="Optional standalone HTML audit report path")
    audit_parser.add_argument("--no-history", action="store_true", help="Do not write dated JSON history copies")
    audit_parser.add_argument("--sqlite-index", help="Optional SQLite index path for audit history")
    audit_parser.add_argument("--cache", action="store_true", help="Enable local HTTP cache for audit requests")
    audit_parser.add_argument("--cache-dir", default=".cache/prospect_machine/http", help="HTTP cache directory")
    audit_parser.add_argument("--cache-ttl-seconds", type=int, default=604_800, help="HTTP cache TTL in seconds")

    compare_parser = subparsers.add_parser("compare-audits", help="Compare two audit JSON reports")
    compare_parser.add_argument("old_report", help="Older audit JSON path")
    compare_parser.add_argument("new_report", help="Newer audit JSON path")
    compare_parser.add_argument("--output", help="Optional CSV output with page-level changes")
    compare_parser.add_argument("--json", dest="json_output", help="Optional JSON comparison output")

    doctor_parser = subparsers.add_parser("doctor", help="Check local setup and writable output folders")
    doctor_parser.add_argument("--json", dest="json_output", help="Optional JSON output path")

    gsc_parser = subparsers.add_parser("gsc", help="Analyze GSC page exports")
    gsc_parser.add_argument("current", help="Current pages export CSV")
    gsc_parser.add_argument("previous", nargs="?", help="Previous pages export CSV")
    gsc_parser.add_argument("-q", "--queries", help="Optional queries export CSV")
    gsc_parser.add_argument("--graphique", help="Optional chart export CSV")
    gsc_parser.add_argument("--pays", help="Optional countries export CSV")
    gsc_parser.add_argument("--appareils", help="Optional devices export CSV")
    gsc_parser.add_argument("--site", default="", help="Site label for HTML report")
    gsc_parser.add_argument("--html", dest="html_output", help="HTML output path")
    gsc_parser.add_argument("--json", dest="json_output", help="JSON output path")
    gsc_parser.add_argument("--output", default="reports/gsc_report.csv", help="CSV output path")
    gsc_parser.add_argument(
        "--niche-stopwords",
        type=parse_csv_list,
        help="Comma-separated niche stopwords added to the generic overlap filter",
    )
    gsc_parser.add_argument(
        "--auto-niche-stopwords",
        action="store_true",
        help="Automatically add tokens present in at least 60%% of analyzed URLs",
    )

    ui_parser = subparsers.add_parser("ui", help="Launch local web UI")
    ui_parser.add_argument("--host", default="127.0.0.1", help="Host to bind the local web UI")
    ui_parser.add_argument("--port", type=int, default=8787, help="Port for the local web UI")

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        if args.command == "discover":
            if not args.niches and not args.domains_file:
                raise CLIError("Le module discover attend soit --niches, soit --domains-file.")

            if args.domains_file:
                results = import_domains_from_file(
                    input_path=args.domains_file,
                    output=args.output,
                )
            else:
                results = discover_domains(
                    niches=parse_csv_list(args.niches),
                    limit=args.limit,
                    output=args.output,
                    provider_name=args.provider,
                    delay=args.delay,
                    query_mode=args.query_mode,
                )
            print(f"{len(results)} domaines exportes vers {args.output}")
            for row in discovery_to_console_rows(results):
                print(row)
            return 0

        if args.command == "qualify":
            results = qualify_domains(
                input_csv=args.input_csv,
                output=args.output,
                json_output=args.json_output,
                mode=args.mode,
                delay=args.delay,
                check_sitemap=args.check_sitemap,
                max_html_bytes=args.max_html_bytes,
                max_total_seconds_per_domain=args.max_total_seconds_per_domain,
                max_total_requests_per_domain=args.max_total_requests_per_domain,
                max_sitemap_urls=args.max_sitemap_urls,
                max_nested_sitemaps=args.max_nested_sitemaps,
            )
            print(f"{len(results)} domaines qualifies exportes vers {args.output}")
            print("Top 5:")
            for item in results[:5]:
                print(f"- {item.score:>3} | {item.domain} | cms={item.cms or 'n/a'} | pages~{item.estimated_pages}")
            return 0

        if args.command == "audit":
            reports = audit_domains(
                input_csv=args.input_csv,
                output_dir=args.output_dir,
                top=args.top,
                min_score=args.min_score,
                mode=args.mode,
                delay=args.delay,
                max_pages=args.max_pages,
                max_depth=args.max_depth,
                max_total_requests_per_domain=args.max_total_requests_per_domain,
                max_links_per_page=args.max_links_per_page,
                max_html_bytes=args.max_html_bytes,
                max_total_seconds_per_domain=args.max_total_seconds_per_domain,
                overlap_enabled=args.overlap_enabled,
                overlap_max_pages=args.overlap_max_pages,
                crawl_source=args.crawl_source,
                sitemap_max_urls=args.sitemap_max_urls,
                respect_robots=not args.skip_robots,
                html_output=args.html_output,
                history=not args.no_history,
                sqlite_index=args.sqlite_index,
                cache_enabled=args.cache,
                cache_dir=args.cache_dir,
                cache_ttl_seconds=args.cache_ttl_seconds,
                site=args.site,
            )
            print(f"{len(reports)} audits ecrits dans {args.output_dir}")
            for report in reports[:5]:
                print(
                    f"- {report.domain} | pages={report.pages_crawled} | score={report.observed_health_score} | "
                    f"findings={len(report.critical_findings)}"
                )
            return 0

        if args.command == "compare-audits":
            comparison = compare_audit_reports(
                old_report_path=args.old_report,
                new_report_path=args.new_report,
                output_csv=args.output,
                output_json=args.json_output,
            )
            print(
                "Comparaison terminee | "
                f"score {comparison['old_observed_health_score']} -> {comparison['new_observed_health_score']} "
                f"(delta={comparison['observed_health_delta']}) | "
                f"improved={len(comparison['improved_pages'])} | "
                f"regressed={len(comparison['regressed_pages'])}"
            )
            return 0

        if args.command == "doctor":
            checks = run_doctor()
            for line in format_doctor_results(checks):
                print(line)
            if args.json_output:
                with open(args.json_output, "w", encoding="utf-8") as handle:
                    json.dump(checks, handle, ensure_ascii=False, indent=2)
            return 0 if all(check.get("ok") for check in checks) else 1

        if args.command == "gsc":
            results = run_gsc_analysis(
                current_csv=args.current,
                previous_csv=args.previous,
                queries_csv=args.queries,
                graphique_csv=args.graphique,
                pays_csv=args.pays,
                appareils_csv=args.appareils,
                output_csv=args.output,
                output_html=args.html_output,
                output_json=args.json_output,
                site_name=args.site,
                niche_stopwords=args.niche_stopwords,
                auto_niche_stopwords=args.auto_niche_stopwords,
            )
            high = sum(1 for item in results if item.priority == "HIGH")
            medium = sum(1 for item in results if item.priority == "MEDIUM")
            print(f"{len(results)} pages analysées | high={high} | medium={medium} | csv={args.output}")
            return 0

        if args.command == "ui":
            launch_ui(host=args.host, port=args.port)
            return 0

        parser.print_help()
        return 1
    except CLIError as exc:
        print(f"Erreur: {exc}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print("Interruption utilisateur.", file=sys.stderr)
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
